name: Release Ansible cross repository test

on:
  pull_request:
    branches:
      - main
    types: [opened]
  workflow_dispatch: # Manual trigger


jobs:
  pr_opened_job:
    runs-on: ubuntu-latest
    env:
      EXIT_STATUS: 0
    steps:
      - name: Checkout linode_api4 repository
        uses: actions/checkout@v3

      - name: update packages
        run: sudo apt-get update -y

      - name: install make
        run: sudo apt-get install -y build-essential

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install linode_api4
        run: make -C path/to/linode_api4 install

      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: linode/ansible_linode
          path: .ansible/collections/ansible_collections/linode/cloud

      - name: install dependencies
        run: make deps

      - name: install ansible dependencies
        run: ansible-galaxy collection install amazon.aws:==6.0.1

      - name: install collection
        run: make install

      - name: replace existing keys
        run: rm -rf ~/.ansible/test && mkdir -p ~/.ansible/test && ssh-keygen -m PEM -q -t rsa -N '' -f ~/.ansible/test/id_rsa

      - name: run tests
        run: |
          make testall
        env:
          LINODE_API_TOKEN: ${{ secrets.DX_LINODE_TOKEN }}
